server:
  port: 8082
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/roberthmerino/msproyecto.git
          searchPaths: config-data
          username: roberthmerino@gmail.com
          password: 190477opor
          default-label: "main"
  security:
    user:
      name: admin
      password: 12345678 
